// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameValidationCode = "validation_codes"

// ValidationCode mapped from table <validation_codes>
type ValidationCode struct {
	ID        int64          `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	CreatedAt *time.Time     `gorm:"column:created_at" json:"created_at"`
	UpdatedAt *time.Time     `gorm:"column:updated_at" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at" json:"deleted_at"`
	Code      string         `gorm:"column:code;not null" json:"code"`
	Email     string         `gorm:"column:email;not null" json:"email"`
	UsedAt    *time.Time     `gorm:"column:used_at" json:"used_at"`
}

// TableName ValidationCode's table name
func (*ValidationCode) TableName() string {
	return TableNameValidationCode
}
